FROM php:7.2.6-fpm

LABEL maintainer="Ryker Rumsey <rykerrumsey@outlook.com>"

RUN apt-get update && apt-get upgrade -y

RUN docker-php-ext-install mbstring \
    && pecl install mongodb \
    && pecl install xdebug-2.6.0 \
    && docker-php-ext-enable mongodb xdebug \
    && apt-get autoremove -y --purge \
    && apt-get clean \
    && rm -Rf /tmp/*
