version: '3'
services:
    web:
        image: nginx:latest
        ports:
            - "8000:80"
        restart: always
        volumes:
            - "./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf"
            - "./web:/web"
        depends_on:
            - "php"
            - "mongodb"
    php:
        build: ./
        restart: always
        volumes:
            - ./web:/web
    composer:
        image: composer
        volumes:
            - ./web/app:/app
        command: install --ignore-platform-reqs
    mongodb:
        image: mongo
        container_name: mongo
        restart: always
        volumes:
            - "./data/db/mongo:/data/db"
            - "./init:/docker-entrypoint-initdb.d"
        environment:
            - MONGO_INITDB_DATABASE=upkeep
        ports:
            - "27020:27017"
        command: --storageEngine wiredTiger
